<?php
/**
 * phpMyAdmin Configuration Fixer
 * File: fix_phpmyadmin.php
 * 
 * Solves: "Cannot connect: invalid settings" and "Access denied for user 'pma'"
 * 
 * This creates a working phpMyAdmin config.inc.php file
 */

echo "=== phpMyAdmin Configuration Fix ===\n\n";

// phpMyAdmin config file location
$configFile = 'C:\\xampp\\phpMyAdmin\\config.inc.php';

// Check if file exists and is writable
if (!file_exists($configFile)) {
    echo "❌ ERROR: phpMyAdmin config file not found at:\n";
    echo "   $configFile\n";
    echo "\nPlease check your XAMPP installation.\n";
    exit(1);
}

if (!is_writable($configFile)) {
    echo "❌ ERROR: Cannot write to phpMyAdmin config file.\n";
    echo "   File: $configFile\n";
    echo "   Please make it writable or edit manually.\n";
    exit(1);
}

echo "Step 1: Backing up current config...\n";

// Create backup
$backup = $configFile . '.backup.' . date('Y-m-d-His');
if (copy($configFile, $backup)) {
    echo "✓ Backup created: $backup\n";
} else {
    echo "⚠ Could not create backup\n";
}

echo "\nStep 2: Creating new phpMyAdmin config...\n";

// Read original config to preserve some settings
$originalConfig = file_get_contents($configFile);

// Generate new config content
$newConfig = <<<'CONFIG'
<?php
/**
 * phpMyAdmin configuration file, generated by Travel Website Setup
 * This uses cookie authentication (you'll be prompted for login)
 */

// Server configuration
$i = 1;

// Authentication type (cookie = prompt for login each time)
$cfg['Servers'][$i]['auth_type'] = 'cookie';

// MySQL server hostname or IP address
$cfg['Servers'][$i]['host'] = 'localhost';

// MySQL port - change to 3307 if that's what XAMPP uses
$cfg['Servers'][$i]['port'] = '3306';

// Socket (leave empty for TCP)
$cfg['Servers'][$i]['socket'] = '';

// MySQL character set
$cfg['Servers'][$i]['compress'] = false;

// Allow/deny connection extensions
$cfg['Servers'][$i]['AllowNoPassword'] = true;

// Set this to enable SQL debugging output
$cfg['Servers'][$i]['verbose'] = 'Travel Website MySQL';

// phpMyAdmin display settings
$cfg['PmaAbsoluteUri'] = '';
$cfg['PmaNoRelation_DisableWarning'] = true;
$cfg['NavigationTreeDefaultTabTable'] = 'structure';
$cfg['NavigationTreeDefaultTabTable2'] = '';
$cfg['BrowsePointerEnable'] = true;
$cfg['BrowseMarkerEnable'] = true;
$cfg['TextareaCols'] = 80;
$cfg['TextareaRows'] = 30;
$cfg['LimitChars'] = 50;
$cfg['DBG']['sql'] = false;
$cfg['GD'] = array();
$cfg['GD']['direct'] = true;

// Default theme
$cfg['ThemeDefault'] = 'pmahomme';
$cfg['ThemePercentage'] = 75;

// Query window size
$cfg['QueryWindowHeight'] = 310;

// Settings for cookie authentication (session configuration)
$cfg['blowfish_secret'] = 'CHANGE_THIS_SECRET_KEY_' . md5(__FILE__);

// Maximum rows to display
$cfg['MaxRows'] = 100;
$cfg['MinDigits'] = 5;
$cfg['MinDigits4Storage'] = 10;

// Allow INSERT, UPDATE, DELETE queries
$cfg['AllowUserDropDatabase'] = false;

// SQL query history
$cfg['QueryHistoryDB'] = false;
$cfg['QueryHistoryMax'] = 25;

// End of phpMyAdmin configuration
CONFIG;

// Write new config
if (file_put_contents($configFile, $newConfig)) {
    echo "✓ New config written\n";
} else {
    echo "❌ Failed to write config file\n";
    exit(1);
}

echo "\nStep 3: Verifying MySQL connectivity...\n";

// Test connection
$mysqli = @new mysqli('localhost', 'root', '', 'mysql', 3306);

if ($mysqli->connect_error) {
    echo "⚠ MySQL connection warning: " . $mysqli->connect_error . "\n";
    echo "  This may cause phpMyAdmin issues.\n";
    echo "  Try starting MySQL from XAMPP Control Panel\n";
} else {
    echo "✓ MySQL is responding\n";
    $mysqli->close();
}

echo "\n=== Fix Complete ===\n";
echo "\nTo use phpMyAdmin:\n";
echo "1. Go to: http://localhost/phpmyadmin\n";
echo "2. You'll see a login prompt\n";
echo "3. Username: root\n";
echo "4. Password: (leave empty if no password set)\n";
echo "5. Click Go\n";
echo "\nIf it still doesn't work:\n";
echo "• Make sure MySQL is running (XAMPP Control Panel)\n";
echo "• Try http://localhost/phpmyadmin/?server=1\n";
echo "• Check your MySQL root password is correct\n";
?>
